[theme]
base="dark"

[server]
enableXsrfProtection=false

[global]
disableWidgetStateWarnings=true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[client]
showErrorDetails = false

[menu]
primaryColor="#ffffff"

[server]
port = 8501

[ui]
hideSidebarNav = true
hideTopBar = true